### PR TITLE
Index page cleanup

### PR DESCRIPTION
**Pull request by Coleyra**
- Used "<?php echo" instead of "<?=" PHP short tag (they aren't always enabled)
- Used ' instead of " for strings without variable name in it
- Modified a bit the procedure to get the language (some PHP noticed was there)

### CODE REVIEW

**Comment by sharkiller** [comment]
awful pull request but whatever

**Comment by Coleyra** [comment]
Why ?

**Comment by sharkiller** [comment]
there is no need for the function change is was shorter and clean. and the <?= is actually designed for this, to not do an echo every 2 lines and if a server dont have that tag enabled is because is prehistoric.

**Comment by SrPatinhas** [comment]
@sharkiller is correct, <?= this is what is when we want to write the variable only, but it was a nice nice point to make a cleaner code, but the <?= probably is better, and when it's possible to have no spaces between lines and code, delete the space to make a fast response to the client request :)

**Comment by Coleyra** [comment]
Well if you prefer <?= let's go for this, but you're closing the door to people without PHP 5.4 and short_tags disabled (PHP 5.3 is still maintain till July 2014, that's not what i call prehistoric).
I'll do a pull request to revert to <?=

@sharkiller I'm sorry but maybe your function was shorter, but not clear at first sight. Those multiple "else return false" were confusing. I changed so you directly see when it return true, and if not always return false.

BTW, next time you think that my pull request is awful, don't merge it, and say why.

@SrPatinhas " delete the space to make a fast response to the client request :)" Well, if you're google maybe you will try to gain 0.000000001ms on your page generation, i don't think we are for now, and having spaces offer a great lisibility to the code.

**Comment by SrPatinhas** [comment]
@Coleyra yes, thats right, but the PHP version don't depend of the server? if we choose one with the most possible newer version, we will not have that problems i think. For example this code  

<pre>
if(array_key_exists('lang', $_GET))     $lang_get   = checklang($_GET["lang"]);
</pre>

cant be change to this way?

<pre>
if(array_key_exists('lang', $_GET))
    $lang_get   = checklang($_GET["lang"]);
</pre>

**Comment by Coleyra** [comment]
Yes it can be changed this way, and that's a better way to do it :)

For the server, of course the website will be ok, but maybe some dev / designer won't have access to a recent version of PHP, and then couldn't help on the website updates.

**Comment by SrPatinhas** [comment]
but they are all merging to the newest version, at least the 5.3 and 5.4

**Comment by sharkiller** [comment]
@Coleyra well if you dont understand is not a problem of the code. you used a useless array_key_exists for get seriously? even the first line of checklang is a isset, if not set return false. then you do in the others if isset checks again because of that array_key_exists.

**Comment by Coleyra** [comment]
Do as you wish.
I'm out of this nonsense project.

**Pull request merged**
