### PR TITLE
Fix gridsystem for mobile devices

### PR DESCRIPTION
**Pull request by frdmn**
This PR contains a fix for the gridsystem which is messed up on the smalles media query for mobile devices.

Before:

After:

### CODE REVIEW

**Comment by frdmn** [comment]
I'll try to get turn the feature articles into an `<ul>` list, to bring back 2 per rows.

**Comment by frdmn** [comment]
No need for that `<ul>` got it all working :)

**Comment by ghost** [comment]
Still a few things that need to be fixed. I'll do this when i get time :smile: Thanks @frdmn

**Comment by ghost** [comment]
Can we delete the branch?

**Comment by frdmn** [comment]
oh sure!

**Pull request closed without merging**
